### ISSUE TITLE
Writing to LiteDB target does nothing. Exceptions visible in the NLog internalLogFile

### ISSUE THREAD

**Issue by A9G-Data-Droid** [cccsdh/NLog.LiteDB#7]
Writing to my LiteDB target does nothing so I configured NLog with `internalLogLevel="Trace" internalLogFile="c:\temp\nlog-internal.log">` and now I am seeing an error that makes me think that the current version of LiteDB is not compatible with this plugin. The `.db` is never created.

**PROJECT:**     Framework 4.8
**LiteDB:**         v5.0.9
**Nlog:**            v4.7.4
**NLog.LiteDB:** v2019.3.22.3 

**ERROR CODE:**
```
2020-09-01 13:41:33.9461 Error Error when writing to LiteDB System.MissingMethodException: Method not found: 'Void LiteDB.LiteDatabase..ctor(System.String, LiteDB.BsonMapper, LiteDB.Logger)'.
   at NLog.LiteDB.LiteDBTarget.<GetCollection>b__49_0(String k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NLog.LiteDB.LiteDBTarget.GetCollection()
   at NLog.LiteDB.LiteDBTarget.Write(LogEventInfo logEvent)
2020-09-01 13:41:36.9345 Info AppDomain Shutting down. Logger closing...
```

**Comment by A9G-Data-Droid** [comment]
After reading Issue #2 I rolled my LiteDB version back to v4.1.4 as this was cited as that last known good version. That resolved the problem I was having. Thus, I believe this current issue is another breaking change in the latest version of LiteDB similar to Issue #2

**Comment by cccsdh** [comment]
We'll take a look at it    There definitely are some major LiteDB updates in v5 release.

**Comment by cccsdh** [comment]
Initiated a branch for the final 4.x LiteDB version.   This is in anticipation of the new version which will target LiteDB 5.x versions.
